### PR TITLE
Fix addresses get api

### LINKED ISSUE #927: The api for checking the addresses /others/ expects case sensitive argument
In my opinion it should be case insensitive.

Example:

https://etherscamdb.info/api/check/0x92d43d2f55e077d1bebc6e348a9f4ff64fd4f21a/
returns
{"success":true,"result":"neutral","type":"address","entries":{}}

https://etherscamdb.info/api/check/0x92d43D2f55E077D1beBC6e348a9F4FF64fD4F21A
returns
{"success":true,"result":"blocked","type":"address","entries":[{"id":4056,"name":"blttrex.us","url":"https://blttrex.us","category":"Trust-Trading","description":"Trust-Trading site","addresses":["0x92d43D2f55E077D1beBC6e348a9F4FF64fD4F21A"],"ip":"198.252.108.77","nameservers":["ns10.hawkhost.com","ns9.hawkhost.com"],"status":"Active"}]}

The website reports the address as a scam, regardless what case is used:
https://etherscamdb.info/address/0x92d43d2f55e077d1bebc6e348a9f4ff64fd4f21a/

### PR DESCRIPTION
**Pull request by hahnmichaelf**
Casts addresses as lowercase in the cache and display to allow for /api/check/ for addresses functionality to be case-insensitive.

Fixes #927 

Now lowercase and uppercase addresses in api both return the same content: 
lowercase

uppercase

### CODE REVIEW

File: run.js [hunk 1]
```diff
@@ -554,15 +554,15 @@ function startWebServer() {
                 var blocked = false;
                 Object.keys(getCache().addresses).forEach(function(address, index) {
                     //They searched for an address
-                    if (req.params.domain == address) {
+                    if (req.params.domain.toLowerCase() == address.toLowerCase()) {
```
Comment (409H) [inline run.js]: Can we make that `===` actually pls
